spring.application.name=CodeLens
server.port=8081
#Here the repo will download temporary
app.ingestion.work-dir=codelens_data/repos

gemini.api.key=AIzaSyDKWrRUS_oXNwQnErNSGr9rCG4QcSragmE

gemini.base-url=https://generativelanguage.googleapis.com/v1beta/models
gemini.model.chat=gemini-2.0-flash
gemini.model.embedding=text-embedding-004